== Spring Cloud Stream with Avro Serialization and Confluent Schema Registry Samples

This repository contains a simple Source and Sink configured with the Kafka binder, Avro serialization and integrated with the Confluent schema registry

=== Prerequisites

* Java 11
* Docker recommended

==== Install Confluent Platform

Follow the instructions https://docs.confluent.io/current/quickstart/index.html[here].  I used the Docker Install.


=== Start the Sink

Build the app

```bash
cd avro-demo-sink
mvn clean package
```

You can run it the terminal:

```bash
java -jar target/avro-demo-sink-0.0.1-SNAPSHOT.jar
```

or in your IDE


=== Start the Source

Build the app

```bash
cd avro-demo-source
mvn clean package
```

You can run it the terminal:

```bash
java -jar target/avro-demo-source-0.0.1-SNAPSHOT.jar
```

or in your IDE


=== Avro Serialization

The `avro-demo-source` is configured with the Maven plugin to generate the `User` class from the schema.
This is basically the same as the Avro tutorial User class. The class was copied to the sink project for convenience.

Take a look at `application.yaml` in each of the apps. For example, the sink configuration is:

```yaml
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: users-topic
          group: users
          consumer:
            useNativeDecoding: true
      kafka:
        bindings:
          input:
            consumer:
              configuration:
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: http://localhost:8081
server.port: 0
```

The `useNativeDecoding: true` is required to bypass the default Spring Cloud Stream Message Converters and use the
`KafkaAvroDeserializer` directly. The source contains corresponding configuration for serialization.

=== Spring Cloud Sleuth.

This is example is also configured to use Spring Cloud Sleuth for end to end tracing. Notice the additional
message headers used for tracing, as shown in the `sink`s console log.






